-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  action character varying NOT NULL,
  target_type character varying,
  target_id character varying,
  old_value jsonb,
  new_value jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blanket_order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  blanket_order_id uuid NOT NULL,
  item_id uuid NOT NULL,
  line_number integer NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  unit_price numeric,
  total_amount numeric,
  monthly_usage numeric DEFAULT 0,
  packing_multiple integer DEFAULT 1,
  order_multiple integer DEFAULT 1,
  min_stock integer DEFAULT 0,
  max_stock integer DEFAULT 0,
  safety_stock integer,
  delivery_schedule text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT blanket_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT blanket_order_items_order_fk FOREIGN KEY (blanket_order_id) REFERENCES public.blanket_orders(id),
  CONSTRAINT blanket_order_items_item_fk FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE TABLE public.blanket_order_lines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  item_code character varying NOT NULL,
  total_quantity integer NOT NULL,
  released_quantity integer DEFAULT 0,
  delivered_quantity integer DEFAULT 0,
  pending_quantity integer DEFAULT (total_quantity - delivered_quantity),
  unit_price numeric,
  line_total numeric DEFAULT ((total_quantity)::numeric * unit_price),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blanket_order_lines_pkey PRIMARY KEY (id),
  CONSTRAINT blanket_order_lines_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.blanket_orders(id),
  CONSTRAINT blanket_order_lines_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.blanket_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_number character varying NOT NULL UNIQUE,
  customer_name character varying NOT NULL,
  customer_code character varying,
  order_date date NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status character varying DEFAULT 'ACTIVE'::character varying,
  total_value numeric,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  sap_doc_no character varying,
  customer_po_number character varying,
  CONSTRAINT blanket_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blanket_releases (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  release_number character varying NOT NULL UNIQUE,
  order_id uuid NOT NULL,
  line_id uuid NOT NULL,
  item_code character varying NOT NULL,
  release_date date NOT NULL,
  requested_delivery_date date NOT NULL,
  actual_delivery_date date,
  requested_quantity integer NOT NULL,
  delivered_quantity integer DEFAULT 0,
  status character varying DEFAULT 'PENDING'::character varying,
  shipment_number character varying,
  tracking_number character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT blanket_releases_pkey PRIMARY KEY (id),
  CONSTRAINT blanket_releases_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.blanket_orders(id),
  CONSTRAINT blanket_releases_line_id_fkey FOREIGN KEY (line_id) REFERENCES public.blanket_order_lines(id),
  CONSTRAINT blanket_releases_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.demand_forecasts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL,
  forecast_date date NOT NULL,
  forecast_period character varying DEFAULT 'MONTHLY'::character varying,
  forecasted_quantity numeric NOT NULL,
  actual_quantity numeric,
  forecast_error numeric,
  forecast_accuracy_pct numeric,
  model_type character varying DEFAULT 'HOLT_WINTERS'::character varying,
  alpha numeric,
  beta numeric,
  gamma numeric,
  lower_bound numeric,
  upper_bound numeric,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT demand_forecasts_pkey PRIMARY KEY (id),
  CONSTRAINT demand_forecasts_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.demand_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL,
  demand_date date NOT NULL,
  period_type character varying DEFAULT 'MONTHLY'::character varying,
  demand_quantity numeric NOT NULL,
  source character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT demand_history_pkey PRIMARY KEY (id),
  CONSTRAINT demand_history_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.inv_approvals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_type character varying NOT NULL,
  entity_id uuid NOT NULL,
  approval_level integer NOT NULL DEFAULT 1,
  approval_sequence integer NOT NULL DEFAULT 1,
  approver_role character varying NOT NULL,
  approver_user_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::approval_status,
  comments text,
  approved_at timestamp with time zone,
  due_date timestamp with time zone,
  escalated_to uuid,
  escalated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT inv_approvals_approver_fkey FOREIGN KEY (approver_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.inv_blanket_release_stock (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  release_id uuid NOT NULL,
  warehouse_id uuid NOT NULL,
  item_code character varying NOT NULL,
  lot_number character varying,
  batch_number character varying,
  quantity_released integer NOT NULL CHECK (quantity_released > 0),
  stock_ledger_id uuid,
  release_status character varying DEFAULT 'PENDING'::character varying,
  validated_at timestamp with time zone,
  validated_by uuid,
  released_at timestamp with time zone,
  released_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT inv_blanket_release_stock_pkey PRIMARY KEY (id),
  CONSTRAINT inv_blanket_release_stock_release_fkey FOREIGN KEY (release_id) REFERENCES public.blanket_releases(id),
  CONSTRAINT inv_blanket_release_stock_warehouse_fkey FOREIGN KEY (warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT inv_blanket_release_stock_ledger_fkey FOREIGN KEY (stock_ledger_id) REFERENCES public.inv_stock_ledger(id),
  CONSTRAINT inv_blanket_release_stock_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.inv_movement_headers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  movement_number character varying NOT NULL UNIQUE,
  movement_date date NOT NULL DEFAULT CURRENT_DATE,
  movement_type character varying NOT NULL,
  source_warehouse_id uuid,
  destination_warehouse_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::movement_status,
  approval_status USER-DEFINED DEFAULT 'PENDING'::approval_status,
  priority character varying DEFAULT 'NORMAL'::character varying,
  reference_document_type character varying,
  reference_document_id uuid,
  reference_document_number character varying,
  reason_code character varying,
  reason_description text,
  notes text,
  requested_by uuid NOT NULL,
  requested_at timestamp with time zone DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  completed_by uuid,
  completed_at timestamp with time zone,
  cancelled_by uuid,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_movement_headers_pkey PRIMARY KEY (id),
  CONSTRAINT inv_movement_headers_source_fkey FOREIGN KEY (source_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT inv_movement_headers_dest_fkey FOREIGN KEY (destination_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT inv_movement_headers_requested_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT inv_movement_headers_approved_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.inv_movement_lines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  header_id uuid NOT NULL,
  line_number integer NOT NULL,
  item_code character varying NOT NULL,
  lot_number character varying,
  batch_number character varying,
  requested_quantity integer NOT NULL CHECK (requested_quantity > 0),
  approved_quantity integer,
  actual_quantity integer,
  unit_cost numeric,
  line_status character varying DEFAULT 'PENDING'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_movement_lines_pkey PRIMARY KEY (id),
  CONSTRAINT inv_movement_lines_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code),
  CONSTRAINT inv_movement_lines_header_fkey FOREIGN KEY (header_id) REFERENCES public.inv_movement_headers(id)
);
CREATE TABLE public.inv_reason_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reason_code character varying NOT NULL UNIQUE,
  reason_category character varying NOT NULL,
  description character varying NOT NULL,
  requires_approval boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inv_reason_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inv_reference_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_type character varying NOT NULL,
  document_number character varying NOT NULL,
  document_date date NOT NULL,
  external_reference character varying,
  description text,
  status character varying DEFAULT 'ACTIVE'::character varying,
  valid_from date,
  valid_until date,
  total_value numeric,
  currency_code character varying DEFAULT 'USD'::character varying,
  customer_code character varying,
  vendor_code character varying,
  attachment_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_reference_documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inv_stock_ledger (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ledger_date timestamp with time zone NOT NULL DEFAULT now(),
  warehouse_id uuid NOT NULL,
  item_code character varying NOT NULL,
  lot_number character varying,
  batch_number character varying,
  transaction_type USER-DEFINED NOT NULL,
  transaction_id uuid,
  transaction_number character varying,
  quantity_change integer NOT NULL,
  quantity_before integer NOT NULL,
  quantity_after integer NOT NULL,
  unit_cost numeric,
  total_value numeric,
  reference_type character varying,
  reference_id uuid,
  reference_number character varying,
  source_warehouse_id uuid,
  destination_warehouse_id uuid,
  reason_code character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT inv_stock_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT inv_stock_ledger_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code),
  CONSTRAINT inv_stock_ledger_warehouse_fkey FOREIGN KEY (warehouse_id) REFERENCES public.inv_warehouses(id)
);
CREATE TABLE public.inv_warehouse_stock (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  warehouse_id uuid NOT NULL,
  item_code character varying NOT NULL,
  lot_number character varying,
  batch_number character varying,
  serial_number character varying,
  quantity_on_hand integer NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),
  quantity_allocated integer NOT NULL DEFAULT 0,
  quantity_reserved integer NOT NULL DEFAULT 0,
  quantity_in_transit integer NOT NULL DEFAULT 0,
  quantity_available integer DEFAULT ((quantity_on_hand - quantity_allocated) - quantity_reserved) CHECK (quantity_available >= 0),
  unit_cost numeric,
  last_receipt_date timestamp with time zone,
  last_issue_date timestamp with time zone,
  expiry_date date,
  manufacture_date date,
  quality_status character varying DEFAULT 'GOOD'::character varying,
  storage_location character varying,
  bin_number character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  row_version integer DEFAULT 1,
  CONSTRAINT inv_warehouse_stock_pkey PRIMARY KEY (id),
  CONSTRAINT inv_warehouse_stock_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code),
  CONSTRAINT inv_warehouse_stock_warehouse_fkey FOREIGN KEY (warehouse_id) REFERENCES public.inv_warehouses(id)
);
CREATE TABLE public.inv_warehouse_types (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type_code character varying NOT NULL UNIQUE,
  type_name character varying NOT NULL,
  category USER-DEFINED NOT NULL,
  description text,
  is_transit_point boolean DEFAULT false,
  is_production_site boolean DEFAULT false,
  can_ship_external boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_warehouse_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inv_warehouses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  warehouse_code character varying NOT NULL UNIQUE,
  warehouse_name character varying NOT NULL,
  warehouse_type_id uuid NOT NULL,
  country_code character varying NOT NULL,
  region character varying,
  city character varying,
  address text,
  postal_code character varying,
  timezone character varying DEFAULT 'UTC'::character varying,
  manager_user_id uuid,
  parent_warehouse_id uuid,
  capacity_units integer,
  current_utilization_pct numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_warehouses_pkey PRIMARY KEY (id),
  CONSTRAINT inv_warehouses_type_fkey FOREIGN KEY (warehouse_type_id) REFERENCES public.inv_warehouse_types(id),
  CONSTRAINT inv_warehouses_parent_fkey FOREIGN KEY (parent_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT inv_warehouses_manager_fkey FOREIGN KEY (manager_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying UNIQUE,
  current_stock integer DEFAULT 0,
  allocated_stock integer DEFAULT 0,
  reserved_stock integer DEFAULT 0,
  in_transit_stock integer DEFAULT 0,
  available_stock integer DEFAULT ((current_stock - allocated_stock) - reserved_stock),
  last_movement_date timestamp with time zone,
  last_movement_type character varying,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL UNIQUE,
  item_name character varying NOT NULL,
  uom character varying DEFAULT 'PCS'::character varying,
  unit_price numeric,
  standard_cost numeric,
  lead_time_days integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  master_serial_no character varying,
  revision character varying,
  part_number character varying,
  CONSTRAINT items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.module_registry (
  module_key character varying NOT NULL,
  display_name character varying NOT NULL,
  parent_module character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT module_registry_pkey PRIMARY KEY (module_key)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'system'::text,
  module text,
  reference_id text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.packing_audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  packing_request_id uuid NOT NULL,
  action_type character varying NOT NULL CHECK (action_type::text = ANY (ARRAY['PACKING_CREATED'::character varying, 'PACKING_REJECTED'::character varying, 'PACKING_STARTED'::character varying, 'BOX_CREATED'::character varying, 'BOX_DELETED'::character varying, 'STICKER_PRINTED'::character varying, 'PACKING_COMPLETED'::character varying, 'STOCK_MOVEMENT_EXECUTED'::character varying]::text[])),
  performed_by uuid NOT NULL,
  role character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT packing_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT packing_audit_logs_request_fkey FOREIGN KEY (packing_request_id) REFERENCES public.packing_requests(id),
  CONSTRAINT packing_audit_logs_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.packing_boxes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  packing_request_id uuid NOT NULL,
  box_number integer NOT NULL CHECK (box_number > 0),
  box_qty numeric NOT NULL CHECK (box_qty > 0::numeric),
  sticker_printed boolean NOT NULL DEFAULT false,
  sticker_printed_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  packing_id text,
  is_transferred boolean DEFAULT false,
  transferred_at timestamp with time zone,
  CONSTRAINT packing_boxes_pkey PRIMARY KEY (id),
  CONSTRAINT packing_boxes_request_fkey FOREIGN KEY (packing_request_id) REFERENCES public.packing_requests(id),
  CONSTRAINT packing_boxes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.packing_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  movement_header_id uuid NOT NULL UNIQUE,
  movement_number character varying NOT NULL,
  item_code character varying NOT NULL,
  total_packed_qty numeric NOT NULL CHECK (total_packed_qty > 0::numeric),
  status character varying NOT NULL DEFAULT 'APPROVED'::character varying CHECK (status::text = ANY (ARRAY['APPROVED'::character varying, 'REJECTED'::character varying, 'PACKING_IN_PROGRESS'::character varying, 'COMPLETED'::character varying]::text[])),
  created_by uuid NOT NULL,
  approved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  operator_remarks text,
  supervisor_remarks text,
  transferred_qty integer DEFAULT 0,
  last_transfer_at timestamp with time zone,
  CONSTRAINT packing_requests_pkey PRIMARY KEY (id),
  CONSTRAINT packing_requests_movement_fkey FOREIGN KEY (movement_header_id) REFERENCES public.inv_movement_headers(id),
  CONSTRAINT packing_requests_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code),
  CONSTRAINT packing_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT packing_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.packing_specifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL UNIQUE,
  item_code text NOT NULL,
  inner_box_length_mm numeric NOT NULL DEFAULT 0,
  inner_box_width_mm numeric NOT NULL DEFAULT 0,
  inner_box_height_mm numeric NOT NULL DEFAULT 0,
  inner_box_quantity integer NOT NULL DEFAULT 0,
  inner_box_net_weight_kg numeric NOT NULL DEFAULT 0,
  outer_box_length_mm numeric NOT NULL DEFAULT 0,
  outer_box_width_mm numeric NOT NULL DEFAULT 0,
  outer_box_height_mm numeric NOT NULL DEFAULT 0,
  outer_box_gross_weight_kg numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  outer_box_quantity integer NOT NULL DEFAULT 0,
  CONSTRAINT packing_specifications_pkey PRIMARY KEY (id),
  CONSTRAINT packing_specifications_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  role_id character varying NOT NULL,
  module character varying NOT NULL,
  action character varying NOT NULL,
  is_allowed boolean DEFAULT true,
  original_module character varying,
  CONSTRAINT permissions_pkey PRIMARY KEY (id),
  CONSTRAINT permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.planning_recommendations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL,
  planning_date date NOT NULL,
  planning_horizon_days integer,
  current_stock numeric,
  reserved_stock numeric,
  forecasted_demand numeric,
  recommended_action character varying NOT NULL,
  recommended_quantity numeric,
  recommended_date date,
  reason text,
  priority character varying DEFAULT 'LOW'::character varying,
  status character varying DEFAULT 'PENDING'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT planning_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT planning_recommendations_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  employee_id character varying UNIQUE,
  email character varying NOT NULL UNIQUE CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  full_name character varying NOT NULL,
  phone character varying,
  department character varying,
  job_title character varying,
  avatar_url text,
  is_active boolean DEFAULT true,
  is_email_verified boolean DEFAULT false,
  must_change_password boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone,
  password_changed_at timestamp with time zone,
  role character varying DEFAULT 'L1'::character varying,
  deleted_at timestamp with time zone,
  shift character varying,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.roles (
  id character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  level integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stock_movements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL,
  movement_type character varying NOT NULL,
  transaction_type character varying NOT NULL,
  quantity integer NOT NULL,
  balance_after integer NOT NULL,
  reference_type character varying,
  reference_id uuid,
  reference_number character varying,
  reason text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT stock_movements_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.system_settings (
  key character varying NOT NULL,
  value jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT system_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.temp_credentials (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  temp_password_hash text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '24:00:00'::interval),
  used_at timestamp with time zone,
  is_used boolean DEFAULT false,
  CONSTRAINT temp_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT temp_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT temp_credentials_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  module_name character varying NOT NULL,
  can_view boolean NOT NULL DEFAULT false,
  can_create boolean NOT NULL DEFAULT false,
  can_edit boolean NOT NULL DEFAULT false,
  can_delete boolean NOT NULL DEFAULT false,
  source_role character varying,
  overridden_by uuid,
  overridden_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  override_mode character varying NOT NULL DEFAULT 'grant'::character varying CHECK (override_mode::text = ANY (ARRAY['grant'::character varying, 'full_control'::character varying]::text[])),
  CONSTRAINT user_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT user_permissions_user_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_permissions_module_fkey FOREIGN KEY (module_name) REFERENCES public.module_registry(module_key),
  CONSTRAINT user_permissions_overrider_fkey FOREIGN KEY (overridden_by) REFERENCES public.profiles(id)
);