-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  action character varying NOT NULL,
  target_type character varying,
  target_id character varying,
  old_value jsonb,
  new_value jsonb,
  ip_address character varying,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blanket_order_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  blanket_order_id uuid NOT NULL,
  item_id uuid NOT NULL,
  line_number integer NOT NULL,
  quantity numeric NOT NULL DEFAULT 0,
  unit_price numeric,
  total_amount numeric,
  monthly_usage numeric DEFAULT 0,
  packing_multiple integer DEFAULT 1,
  order_multiple integer DEFAULT 1,
  min_stock integer DEFAULT 0,
  max_stock integer DEFAULT 0,
  safety_stock integer,
  delivery_schedule text,
  notes text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT blanket_order_items_pkey PRIMARY KEY (id),
  CONSTRAINT blanket_order_items_order_fk FOREIGN KEY (blanket_order_id) REFERENCES public.blanket_orders(id),
  CONSTRAINT blanket_order_items_item_fk FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE TABLE public.blanket_order_lines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  item_code character varying NOT NULL,
  total_quantity integer NOT NULL,
  released_quantity integer DEFAULT 0,
  delivered_quantity integer DEFAULT 0,
  pending_quantity integer DEFAULT (total_quantity - delivered_quantity),
  unit_price numeric,
  line_total numeric DEFAULT ((total_quantity)::numeric * unit_price),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT blanket_order_lines_pkey PRIMARY KEY (id),
  CONSTRAINT blanket_order_lines_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.blanket_orders(id),
  CONSTRAINT blanket_order_lines_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.blanket_orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_number character varying NOT NULL UNIQUE,
  customer_name character varying NOT NULL,
  customer_code character varying,
  order_date date NOT NULL,
  start_date date NOT NULL,
  end_date date NOT NULL,
  status character varying DEFAULT 'ACTIVE'::character varying,
  total_value numeric,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  sap_doc_no character varying,
  customer_po_number character varying,
  CONSTRAINT blanket_orders_pkey PRIMARY KEY (id)
);
CREATE TABLE public.blanket_releases (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  release_number character varying NOT NULL UNIQUE,
  order_id uuid NOT NULL,
  line_id uuid NOT NULL,
  item_code character varying NOT NULL,
  release_date date NOT NULL,
  requested_delivery_date date NOT NULL,
  actual_delivery_date date,
  requested_quantity integer NOT NULL,
  delivered_quantity integer DEFAULT 0,
  status character varying DEFAULT 'PENDING'::character varying,
  shipment_number character varying,
  tracking_number character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT blanket_releases_pkey PRIMARY KEY (id),
  CONSTRAINT blanket_releases_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.blanket_orders(id),
  CONSTRAINT blanket_releases_line_id_fkey FOREIGN KEY (line_id) REFERENCES public.blanket_order_lines(id),
  CONSTRAINT blanket_releases_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.demand_forecasts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL,
  forecast_date date NOT NULL,
  forecast_period character varying DEFAULT 'MONTHLY'::character varying,
  forecasted_quantity numeric NOT NULL,
  actual_quantity numeric,
  forecast_error numeric,
  forecast_accuracy_pct numeric,
  model_type character varying DEFAULT 'HOLT_WINTERS'::character varying,
  alpha numeric,
  beta numeric,
  gamma numeric,
  lower_bound numeric,
  upper_bound numeric,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT demand_forecasts_pkey PRIMARY KEY (id),
  CONSTRAINT demand_forecasts_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.demand_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL,
  demand_date date NOT NULL,
  period_type character varying DEFAULT 'MONTHLY'::character varying,
  demand_quantity numeric NOT NULL,
  source character varying,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT demand_history_pkey PRIMARY KEY (id),
  CONSTRAINT demand_history_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.dispatch_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  entity_type character varying NOT NULL CHECK (entity_type::text = ANY (ARRAY['MASTER_PACKING_LIST'::character varying, 'PROFORMA_INVOICE'::character varying, 'PALLET'::character varying, 'STOCK_MOVEMENT'::character varying, 'DISPATCH'::character varying]::text[])),
  entity_id uuid NOT NULL,
  entity_number character varying,
  action character varying NOT NULL CHECK (action::text = ANY (ARRAY['CREATED'::character varying, 'CONFIRMED'::character varying, 'PRINTED'::character varying, 'DISPATCHED'::character varying, 'CANCELLED'::character varying, 'PALLET_RELEASED'::character varying, 'STOCK_MOVED'::character varying, 'EMAIL_SENT'::character varying, 'STATUS_CHANGED'::character varying, 'UPDATED'::character varying, 'PALLET_LOCKED'::character varying, 'PALLET_ASSIGNED'::character varying]::text[])),
  from_status character varying,
  to_status character varying,
  performed_by uuid NOT NULL,
  performed_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  ip_address character varying,
  correlation_id uuid,
  parent_audit_id uuid,
  CONSTRAINT dispatch_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT dispatch_audit_log_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.profiles(id),
  CONSTRAINT dispatch_audit_log_parent_audit_id_fkey FOREIGN KEY (parent_audit_id) REFERENCES public.dispatch_audit_log(id)
);
CREATE TABLE public.email_dispatch_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proforma_invoice_id uuid,
  proforma_number text,
  recipients ARRAY NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['sent'::text, 'failed'::text])),
  resend_message_id text,
  error_message text,
  sent_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT email_dispatch_log_pkey PRIMARY KEY (id),
  CONSTRAINT email_dispatch_log_proforma_invoice_id_fkey FOREIGN KEY (proforma_invoice_id) REFERENCES public.pack_proforma_invoices(id)
);
CREATE TABLE public.idempotency_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  idempotency_key uuid NOT NULL,
  operation_type text NOT NULL,
  entity_id uuid,
  status text NOT NULL DEFAULT 'PROCESSING'::text CHECK (status = ANY (ARRAY['PROCESSING'::text, 'SUCCESS'::text, 'FAILED'::text])),
  result_data jsonb DEFAULT '{}'::jsonb,
  error_message text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '24:00:00'::interval),
  CONSTRAINT idempotency_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inv_approvals (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_type character varying NOT NULL,
  entity_id uuid NOT NULL,
  approval_level integer NOT NULL DEFAULT 1,
  approval_sequence integer NOT NULL DEFAULT 1,
  approver_role character varying NOT NULL,
  approver_user_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::approval_status,
  comments text,
  approved_at timestamp with time zone,
  due_date timestamp with time zone,
  escalated_to uuid,
  escalated_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT inv_approvals_approver_fkey FOREIGN KEY (approver_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.inv_blanket_release_stock (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  release_id uuid NOT NULL,
  warehouse_id uuid NOT NULL,
  item_code character varying NOT NULL,
  lot_number character varying,
  batch_number character varying,
  quantity_released integer NOT NULL CHECK (quantity_released > 0),
  stock_ledger_id uuid,
  release_status character varying DEFAULT 'PENDING'::character varying,
  validated_at timestamp with time zone,
  validated_by uuid,
  released_at timestamp with time zone,
  released_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT inv_blanket_release_stock_pkey PRIMARY KEY (id),
  CONSTRAINT inv_blanket_release_stock_release_fkey FOREIGN KEY (release_id) REFERENCES public.blanket_releases(id),
  CONSTRAINT inv_blanket_release_stock_warehouse_fkey FOREIGN KEY (warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT inv_blanket_release_stock_ledger_fkey FOREIGN KEY (stock_ledger_id) REFERENCES public.inv_stock_ledger(id),
  CONSTRAINT inv_blanket_release_stock_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.inv_movement_approvals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  movement_id uuid NOT NULL,
  approver_id uuid NOT NULL,
  action text NOT NULL CHECK (action = ANY (ARRAY['APPROVED'::text, 'PARTIALLY_APPROVED'::text, 'REJECTED'::text])),
  approved_qty integer NOT NULL DEFAULT 0,
  rejected_qty integer NOT NULL DEFAULT 0,
  requested_qty integer NOT NULL DEFAULT 0,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT inv_movement_approvals_pkey PRIMARY KEY (id),
  CONSTRAINT inv_movement_approvals_movement_id_fkey FOREIGN KEY (movement_id) REFERENCES public.inv_movement_headers(id)
);
CREATE TABLE public.inv_movement_headers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  movement_number character varying NOT NULL UNIQUE,
  movement_date date NOT NULL DEFAULT CURRENT_DATE,
  movement_type character varying NOT NULL,
  source_warehouse_id uuid,
  destination_warehouse_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::movement_status,
  approval_status USER-DEFINED DEFAULT 'PENDING'::approval_status,
  priority character varying DEFAULT 'NORMAL'::character varying,
  reference_document_type character varying,
  reference_document_id uuid,
  reference_document_number character varying,
  reason_code character varying,
  reason_description text,
  notes text,
  requested_by uuid NOT NULL,
  requested_at timestamp with time zone DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  completed_by uuid,
  completed_at timestamp with time zone,
  cancelled_by uuid,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  supervisor_note text,
  CONSTRAINT inv_movement_headers_pkey PRIMARY KEY (id),
  CONSTRAINT inv_movement_headers_source_fkey FOREIGN KEY (source_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT inv_movement_headers_dest_fkey FOREIGN KEY (destination_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT inv_movement_headers_requested_fkey FOREIGN KEY (requested_by) REFERENCES public.profiles(id),
  CONSTRAINT inv_movement_headers_approved_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.inv_movement_lines (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  header_id uuid NOT NULL,
  line_number integer NOT NULL,
  item_code character varying NOT NULL,
  lot_number character varying,
  batch_number character varying,
  requested_quantity integer NOT NULL CHECK (requested_quantity > 0),
  approved_quantity integer,
  actual_quantity integer,
  unit_cost numeric,
  line_status character varying DEFAULT 'PENDING'::character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_movement_lines_pkey PRIMARY KEY (id),
  CONSTRAINT inv_movement_lines_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code),
  CONSTRAINT inv_movement_lines_header_fkey FOREIGN KEY (header_id) REFERENCES public.inv_movement_headers(id)
);
CREATE TABLE public.inv_reason_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reason_code character varying NOT NULL UNIQUE,
  reason_category character varying NOT NULL,
  description character varying NOT NULL,
  requires_approval boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inv_reason_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inv_reference_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  document_type character varying NOT NULL,
  document_number character varying NOT NULL,
  document_date date NOT NULL,
  external_reference character varying,
  description text,
  status character varying DEFAULT 'ACTIVE'::character varying,
  valid_from date,
  valid_until date,
  total_value numeric,
  currency_code character varying DEFAULT 'USD'::character varying,
  customer_code character varying,
  vendor_code character varying,
  attachment_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_reference_documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inv_stock_ledger (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  ledger_date timestamp with time zone NOT NULL DEFAULT now(),
  warehouse_id uuid NOT NULL,
  item_code character varying NOT NULL,
  lot_number character varying,
  batch_number character varying,
  transaction_type USER-DEFINED NOT NULL,
  transaction_id uuid,
  transaction_number character varying,
  quantity_change integer NOT NULL,
  quantity_before integer NOT NULL,
  quantity_after integer NOT NULL,
  unit_cost numeric,
  total_value numeric,
  reference_type character varying,
  reference_id uuid,
  reference_number character varying,
  source_warehouse_id uuid,
  destination_warehouse_id uuid,
  reason_code character varying,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT inv_stock_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT inv_stock_ledger_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code),
  CONSTRAINT inv_stock_ledger_warehouse_fkey FOREIGN KEY (warehouse_id) REFERENCES public.inv_warehouses(id)
);
CREATE TABLE public.inv_warehouse_stock (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  warehouse_id uuid NOT NULL,
  item_code character varying NOT NULL,
  lot_number character varying,
  batch_number character varying,
  serial_number character varying,
  quantity_on_hand integer NOT NULL DEFAULT 0 CHECK (quantity_on_hand >= 0),
  quantity_allocated integer NOT NULL DEFAULT 0,
  quantity_reserved integer NOT NULL DEFAULT 0,
  quantity_in_transit integer NOT NULL DEFAULT 0,
  quantity_available integer DEFAULT ((quantity_on_hand - quantity_allocated) - quantity_reserved) CHECK (quantity_available >= 0),
  unit_cost numeric,
  last_receipt_date timestamp with time zone,
  last_issue_date timestamp with time zone,
  expiry_date date,
  manufacture_date date,
  quality_status character varying DEFAULT 'GOOD'::character varying,
  storage_location character varying,
  bin_number character varying,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  row_version integer DEFAULT 1,
  CONSTRAINT inv_warehouse_stock_pkey PRIMARY KEY (id),
  CONSTRAINT inv_warehouse_stock_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code),
  CONSTRAINT inv_warehouse_stock_warehouse_fkey FOREIGN KEY (warehouse_id) REFERENCES public.inv_warehouses(id)
);
CREATE TABLE public.inv_warehouse_types (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  type_code character varying NOT NULL UNIQUE,
  type_name character varying NOT NULL,
  category USER-DEFINED NOT NULL,
  description text,
  is_transit_point boolean DEFAULT false,
  is_production_site boolean DEFAULT false,
  can_ship_external boolean DEFAULT false,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_warehouse_types_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inv_warehouses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  warehouse_code character varying NOT NULL UNIQUE,
  warehouse_name character varying NOT NULL,
  warehouse_type_id uuid NOT NULL,
  country_code character varying NOT NULL,
  region character varying,
  city character varying,
  address text,
  postal_code character varying,
  timezone character varying DEFAULT 'UTC'::character varying,
  manager_user_id uuid,
  parent_warehouse_id uuid,
  capacity_units integer,
  current_utilization_pct numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  is_deleted boolean DEFAULT false,
  deleted_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT inv_warehouses_pkey PRIMARY KEY (id),
  CONSTRAINT inv_warehouses_type_fkey FOREIGN KEY (warehouse_type_id) REFERENCES public.inv_warehouse_types(id),
  CONSTRAINT inv_warehouses_parent_fkey FOREIGN KEY (parent_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT inv_warehouses_manager_fkey FOREIGN KEY (manager_user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.inventory (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying UNIQUE,
  current_stock integer DEFAULT 0,
  allocated_stock integer DEFAULT 0,
  reserved_stock integer DEFAULT 0,
  in_transit_stock integer DEFAULT 0,
  available_stock integer DEFAULT ((current_stock - allocated_stock) - reserved_stock),
  last_movement_date timestamp with time zone,
  last_movement_type character varying,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL UNIQUE,
  item_name character varying NOT NULL,
  uom character varying DEFAULT 'PCS'::character varying,
  unit_price numeric,
  standard_cost numeric,
  lead_time_days integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  master_serial_no character varying,
  revision character varying,
  part_number character varying,
  weight numeric,
  CONSTRAINT items_pkey PRIMARY KEY (id)
);
CREATE TABLE public.master_packing_list_pallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mpl_id uuid NOT NULL,
  pallet_id uuid NOT NULL,
  pallet_number character varying NOT NULL,
  item_code character varying NOT NULL,
  item_name character varying,
  quantity integer NOT NULL,
  container_count integer NOT NULL,
  net_weight_kg numeric NOT NULL DEFAULT 0,
  gross_weight_kg numeric NOT NULL DEFAULT 0,
  inner_box_details jsonb DEFAULT '[]'::jsonb,
  inner_box_qty integer,
  contract_outer_qty integer,
  line_number integer NOT NULL DEFAULT 1,
  status character varying NOT NULL DEFAULT 'ACTIVE'::character varying CHECK (status::text = ANY (ARRAY['ACTIVE'::character varying, 'RELEASED'::character varying]::text[])),
  released_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT master_packing_list_pallets_pkey PRIMARY KEY (id),
  CONSTRAINT master_packing_list_pallets_mpl_id_fkey FOREIGN KEY (mpl_id) REFERENCES public.master_packing_lists(id),
  CONSTRAINT master_packing_list_pallets_pallet_id_fkey FOREIGN KEY (pallet_id) REFERENCES public.pack_pallets(id)
);
CREATE TABLE public.master_packing_lists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  mpl_number character varying NOT NULL UNIQUE,
  packing_list_id uuid NOT NULL,
  packing_list_data_id uuid,
  invoice_number character varying,
  po_number character varying,
  total_pallets integer NOT NULL DEFAULT 0,
  total_containers integer NOT NULL DEFAULT 0,
  total_quantity integer NOT NULL DEFAULT 0,
  total_net_weight_kg numeric NOT NULL DEFAULT 0,
  total_gross_weight_kg numeric NOT NULL DEFAULT 0,
  item_code character varying NOT NULL,
  item_name character varying,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'CONFIRMED'::character varying, 'PRINTED'::character varying, 'DISPATCHED'::character varying, 'CANCELLED'::character varying]::text[])),
  printed_at timestamp with time zone,
  printed_by uuid,
  print_count integer NOT NULL DEFAULT 0,
  dispatched_at timestamp with time zone,
  dispatched_by uuid,
  proforma_invoice_id uuid,
  confirmed_at timestamp with time zone,
  confirmed_by uuid,
  cancelled_at timestamp with time zone,
  cancelled_by uuid,
  cancellation_reason text,
  extra_data jsonb DEFAULT '{}'::jsonb,
  notes text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  row_version integer NOT NULL DEFAULT 1,
  CONSTRAINT master_packing_lists_pkey PRIMARY KEY (id),
  CONSTRAINT master_packing_lists_packing_list_id_fkey FOREIGN KEY (packing_list_id) REFERENCES public.pack_packing_lists(id),
  CONSTRAINT master_packing_lists_packing_list_data_id_fkey FOREIGN KEY (packing_list_data_id) REFERENCES public.pack_packing_list_data(id),
  CONSTRAINT master_packing_lists_printed_by_fkey FOREIGN KEY (printed_by) REFERENCES public.profiles(id),
  CONSTRAINT master_packing_lists_dispatched_by_fkey FOREIGN KEY (dispatched_by) REFERENCES public.profiles(id),
  CONSTRAINT master_packing_lists_proforma_invoice_id_fkey FOREIGN KEY (proforma_invoice_id) REFERENCES public.pack_proforma_invoices(id),
  CONSTRAINT master_packing_lists_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.profiles(id),
  CONSTRAINT master_packing_lists_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.profiles(id),
  CONSTRAINT master_packing_lists_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT master_packing_lists_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.module_registry (
  module_key character varying NOT NULL,
  display_name character varying NOT NULL,
  parent_module character varying,
  sort_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT module_registry_pkey PRIMARY KEY (module_key)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL DEFAULT 'system'::text,
  module text,
  reference_id text,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamp with time zone,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.operation_session_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['session_created'::text, 'session_updated'::text, 'session_completed'::text, 'session_abandoned'::text, 'session_expired'::text, 'conflict_detected'::text])),
  event_data jsonb DEFAULT '{}'::jsonb,
  version_at integer NOT NULL DEFAULT 1,
  user_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT operation_session_events_pkey PRIMARY KEY (id),
  CONSTRAINT operation_session_events_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.operation_sessions(id),
  CONSTRAINT operation_session_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.operation_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_type text NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'in_progress'::text, 'completed'::text, 'abandoned'::text])),
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  session_data jsonb NOT NULL DEFAULT '{}'::jsonb,
  user_id uuid NOT NULL,
  entity_id text,
  entity_type text,
  idempotency_key text UNIQUE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  last_activity_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  expires_at timestamp with time zone DEFAULT (now() + '24:00:00'::interval),
  CONSTRAINT operation_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT operation_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.pack_aggregation_counters (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_code character varying NOT NULL,
  contract_config_id uuid NOT NULL,
  total_containers integer NOT NULL DEFAULT 0,
  total_quantity integer NOT NULL DEFAULT 0,
  current_pallet_qty integer NOT NULL DEFAULT 0,
  pallets_completed integer NOT NULL DEFAULT 0,
  pallets_open integer NOT NULL DEFAULT 0,
  pallet_fill_pct numeric NOT NULL DEFAULT 0,
  adjustment_needed boolean NOT NULL DEFAULT false,
  adjustment_qty integer NOT NULL DEFAULT 0,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pack_aggregation_counters_pkey PRIMARY KEY (id),
  CONSTRAINT pack_aggregation_counters_contract_config_id_fkey FOREIGN KEY (contract_config_id) REFERENCES public.pack_contract_configs(id)
);
CREATE TABLE public.pack_containers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  container_number character varying NOT NULL UNIQUE,
  movement_header_id uuid NOT NULL,
  movement_number character varying NOT NULL,
  packing_request_id uuid,
  packing_box_id uuid,
  item_id uuid NOT NULL,
  item_code character varying NOT NULL,
  contract_config_id uuid,
  quantity integer NOT NULL CHECK (quantity > 0),
  is_adjustment boolean NOT NULL DEFAULT false,
  container_type character varying NOT NULL DEFAULT 'INNER_BOX'::character varying CHECK (container_type::text = ANY (ARRAY['INNER_BOX'::character varying, 'ADJUSTMENT_BOX'::character varying]::text[])),
  sticker_printed boolean NOT NULL DEFAULT false,
  sticker_printed_at timestamp with time zone,
  sticker_data jsonb DEFAULT '{}'::jsonb,
  current_warehouse_id uuid,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  reference_doc_type character varying,
  reference_doc_number character varying,
  packing_spec_id uuid,
  CONSTRAINT pack_containers_pkey PRIMARY KEY (id),
  CONSTRAINT pack_containers_movement_header_id_fkey FOREIGN KEY (movement_header_id) REFERENCES public.inv_movement_headers(id),
  CONSTRAINT pack_containers_packing_request_id_fkey FOREIGN KEY (packing_request_id) REFERENCES public.packing_requests(id),
  CONSTRAINT pack_containers_packing_box_id_fkey FOREIGN KEY (packing_box_id) REFERENCES public.packing_boxes(id),
  CONSTRAINT pack_containers_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id),
  CONSTRAINT pack_containers_contract_config_id_fkey FOREIGN KEY (contract_config_id) REFERENCES public.pack_contract_configs(id),
  CONSTRAINT pack_containers_current_warehouse_id_fkey FOREIGN KEY (current_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT pack_containers_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT pack_containers_packing_spec_id_fkey FOREIGN KEY (packing_spec_id) REFERENCES public.packing_specifications(id)
);
CREATE TABLE public.pack_contract_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL,
  item_code character varying NOT NULL,
  contract_outer_qty integer NOT NULL CHECK (contract_outer_qty > 0),
  inner_box_qty integer NOT NULL CHECK (inner_box_qty > 0),
  full_containers_per_pallet integer DEFAULT (floor(((contract_outer_qty)::numeric / (inner_box_qty)::numeric)))::integer,
  adjustment_qty integer DEFAULT (contract_outer_qty % inner_box_qty),
  customer_code character varying,
  customer_name character varying,
  blanket_order_id uuid,
  effective_from date NOT NULL DEFAULT CURRENT_DATE,
  effective_to date,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT pack_contract_configs_pkey PRIMARY KEY (id),
  CONSTRAINT pack_contract_configs_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id),
  CONSTRAINT pack_contract_configs_blanket_order_id_fkey FOREIGN KEY (blanket_order_id) REFERENCES public.blanket_orders(id),
  CONSTRAINT pack_contract_configs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT pack_contract_configs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pack_dispatch_movements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proforma_id uuid NOT NULL,
  movement_header_id uuid NOT NULL,
  source_warehouse_id uuid NOT NULL,
  dest_warehouse_id uuid NOT NULL,
  item_code character varying NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  pallet_count integer NOT NULL,
  stock_ledger_id uuid,
  executed_at timestamp with time zone NOT NULL DEFAULT now(),
  executed_by uuid NOT NULL,
  CONSTRAINT pack_dispatch_movements_pkey PRIMARY KEY (id),
  CONSTRAINT pack_dispatch_movements_source_warehouse_id_fkey FOREIGN KEY (source_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT pack_dispatch_movements_dest_warehouse_id_fkey FOREIGN KEY (dest_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT pack_dispatch_movements_proforma_id_fkey FOREIGN KEY (proforma_id) REFERENCES public.pack_proforma_invoices(id),
  CONSTRAINT pack_dispatch_movements_movement_header_id_fkey FOREIGN KEY (movement_header_id) REFERENCES public.inv_movement_headers(id),
  CONSTRAINT pack_dispatch_movements_stock_ledger_id_fkey FOREIGN KEY (stock_ledger_id) REFERENCES public.inv_stock_ledger(id),
  CONSTRAINT pack_dispatch_movements_executed_by_fkey FOREIGN KEY (executed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pack_email_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type character varying NOT NULL CHECK (event_type::text = ANY (ARRAY['PACKING_LIST_GENERATED'::character varying, 'INVOICE_GENERATED'::character varying, 'PROFORMA_GENERATED'::character varying, 'STOCK_MOVED_TRANSIT'::character varying, 'PALLET_READY'::character varying, 'ADJUSTMENT_REQUIRED'::character varying]::text[])),
  reference_type character varying NOT NULL,
  reference_id uuid NOT NULL,
  reference_number character varying NOT NULL,
  recipients jsonb NOT NULL DEFAULT '[]'::jsonb,
  subject character varying NOT NULL,
  body_html text,
  body_text text,
  trace_data jsonb DEFAULT '{}'::jsonb,
  status character varying NOT NULL DEFAULT 'PENDING'::character varying CHECK (status::text = ANY (ARRAY['PENDING'::character varying, 'SENT'::character varying, 'FAILED'::character varying, 'SKIPPED'::character varying]::text[])),
  sent_at timestamp with time zone,
  error_message text,
  retry_count integer NOT NULL DEFAULT 0,
  max_retries integer NOT NULL DEFAULT 3,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pack_email_queue_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pack_engine_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  event_type character varying NOT NULL,
  aggregate_type character varying NOT NULL,
  aggregate_id uuid NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  performed_by uuid,
  performed_at timestamp with time zone NOT NULL DEFAULT now(),
  correlation_id uuid,
  causation_id uuid,
  CONSTRAINT pack_engine_events_pkey PRIMARY KEY (id),
  CONSTRAINT pack_engine_events_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pack_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  invoice_number character varying NOT NULL UNIQUE,
  packing_list_id uuid NOT NULL,
  customer_code character varying,
  customer_name character varying,
  customer_po_number character varying,
  blanket_order_id uuid,
  subtotal numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  total_amount numeric NOT NULL DEFAULT 0,
  currency_code character varying NOT NULL DEFAULT 'USD'::character varying,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'CONFIRMED'::character varying, 'PROFORMA_LINKED'::character varying, 'CANCELLED'::character varying]::text[])),
  total_pallets integer NOT NULL DEFAULT 0,
  total_quantity integer NOT NULL DEFAULT 0,
  total_gross_weight_kg numeric DEFAULT 0,
  invoice_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  confirmed_at timestamp with time zone,
  confirmed_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pack_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT pack_invoices_packing_list_id_fkey FOREIGN KEY (packing_list_id) REFERENCES public.pack_packing_lists(id),
  CONSTRAINT pack_invoices_blanket_order_id_fkey FOREIGN KEY (blanket_order_id) REFERENCES public.blanket_orders(id),
  CONSTRAINT pack_invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT pack_invoices_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pack_packing_list_data (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  packing_list_id uuid NOT NULL UNIQUE,
  exporter_name character varying NOT NULL DEFAULT 'AUTOCRAT ENGINEERS'::character varying,
  exporter_address text NOT NULL DEFAULT 'NO. 21 & 22, Export Promotion Industrial Park, Phase - I, Whitefield, Bangalore-560066, KARNATAKA - INDIA'::text,
  exporter_phone character varying NOT NULL DEFAULT 'PH 91 80 43330127'::character varying,
  exporter_email character varying NOT NULL DEFAULT 'dispatch@autocratengineers.in'::character varying,
  exporter_gstin character varying NOT NULL DEFAULT '29ABLPK6831H1ZB'::character varying,
  exporter_pan character varying DEFAULT 'ABLPK6831H'::character varying,
  exporter_ref character varying DEFAULT '-NIL-'::character varying,
  exporter_iec_code character varying DEFAULT '0702002747'::character varying,
  exporter_ad_code character varying DEFAULT '6361504-8400009'::character varying,
  invoice_number character varying,
  invoice_date date,
  purchase_order_number character varying,
  purchase_order_date date,
  vendor_number character varying,
  consignee_name character varying,
  consignee_address text,
  consignee_phone character varying,
  buyer_name character varying,
  buyer_phone character varying,
  buyer_email character varying,
  bill_to_name character varying,
  bill_to_address text,
  ship_via character varying,
  pre_carriage_by character varying DEFAULT 'Road'::character varying,
  place_of_receipt character varying DEFAULT 'BANGALORE'::character varying,
  country_of_origin character varying NOT NULL DEFAULT 'INDIA'::character varying,
  country_of_destination character varying,
  vessel_flight_no character varying,
  port_of_loading character varying DEFAULT 'BANGALORE, ICD'::character varying,
  terms_of_delivery character varying DEFAULT 'DDP'::character varying,
  payment_terms character varying DEFAULT 'Net-30'::character varying,
  port_of_discharge character varying,
  final_destination character varying,
  mode_of_transport character varying DEFAULT 'Sea'::character varying,
  item_description_header character varying DEFAULT 'PRECISION MACHINED COMPONENTS'::character varying,
  item_description_sub_header character varying DEFAULT '(OTHERS FUELING COMPONENTS)'::character varying,
  batch_number character varying,
  notes text,
  extra_data jsonb DEFAULT '{}'::jsonb,
  is_finalized boolean NOT NULL DEFAULT false,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  freight_forwarder text,
  CONSTRAINT pack_packing_list_data_pkey PRIMARY KEY (id),
  CONSTRAINT pack_packing_list_data_packing_list_id_fkey FOREIGN KEY (packing_list_id) REFERENCES public.pack_packing_lists(id),
  CONSTRAINT pack_packing_list_data_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT pack_packing_list_data_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pack_packing_list_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  packing_list_id uuid NOT NULL,
  pallet_id uuid NOT NULL,
  item_code character varying NOT NULL,
  item_name character varying,
  quantity integer NOT NULL,
  container_count integer NOT NULL,
  gross_weight_kg numeric,
  net_weight_kg numeric,
  line_number integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pack_packing_list_items_pkey PRIMARY KEY (id),
  CONSTRAINT pack_packing_list_items_pallet_id_fkey FOREIGN KEY (pallet_id) REFERENCES public.pack_pallets(id),
  CONSTRAINT pack_packing_list_items_packing_list_id_fkey FOREIGN KEY (packing_list_id) REFERENCES public.pack_packing_lists(id)
);
CREATE TABLE public.pack_packing_list_pallet_details (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  packing_list_data_id uuid NOT NULL,
  packing_list_id uuid NOT NULL,
  pallet_id uuid NOT NULL,
  pallet_number character varying NOT NULL,
  carton_number character varying,
  batch_number character varying,
  item_code character varying NOT NULL,
  item_name character varying,
  part_number character varying,
  master_serial_no character varying,
  hts_code character varying,
  part_revision character varying,
  num_pallets integer NOT NULL DEFAULT 1,
  qty_per_pallet integer NOT NULL DEFAULT 0,
  total_containers integer NOT NULL DEFAULT 0,
  pallet_length_cm numeric,
  pallet_width_cm numeric,
  pallet_height_cm numeric,
  net_weight_kg numeric NOT NULL DEFAULT 0,
  gross_weight_kg numeric NOT NULL DEFAULT 0,
  invoice_number character varying,
  po_number character varying,
  line_number integer NOT NULL DEFAULT 1,
  extra_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pack_packing_list_pallet_details_pkey PRIMARY KEY (id),
  CONSTRAINT pack_packing_list_pallet_details_packing_list_data_id_fkey FOREIGN KEY (packing_list_data_id) REFERENCES public.pack_packing_list_data(id),
  CONSTRAINT pack_packing_list_pallet_details_packing_list_id_fkey FOREIGN KEY (packing_list_id) REFERENCES public.pack_packing_lists(id),
  CONSTRAINT pack_packing_list_pallet_details_pallet_id_fkey FOREIGN KEY (pallet_id) REFERENCES public.pack_pallets(id)
);
CREATE TABLE public.pack_packing_lists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  packing_list_number character varying NOT NULL UNIQUE,
  customer_code character varying,
  customer_name character varying,
  blanket_order_id uuid,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'CONFIRMED'::character varying, 'INVOICED'::character varying, 'CANCELLED'::character varying]::text[])),
  total_pallets integer NOT NULL DEFAULT 0,
  total_containers integer NOT NULL DEFAULT 0,
  total_quantity integer NOT NULL DEFAULT 0,
  total_gross_weight_kg numeric DEFAULT 0,
  total_net_weight_kg numeric DEFAULT 0,
  picking_draft_generated boolean NOT NULL DEFAULT false,
  picking_draft_data jsonb DEFAULT '{}'::jsonb,
  dispatch_date date,
  vehicle_number character varying,
  driver_name character varying,
  seal_number character varying,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  confirmed_at timestamp with time zone,
  confirmed_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pack_packing_lists_pkey PRIMARY KEY (id),
  CONSTRAINT pack_packing_lists_blanket_order_id_fkey FOREIGN KEY (blanket_order_id) REFERENCES public.blanket_orders(id),
  CONSTRAINT pack_packing_lists_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT pack_packing_lists_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pack_pallet_containers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pallet_id uuid NOT NULL,
  container_id uuid NOT NULL UNIQUE,
  position_sequence integer NOT NULL,
  assigned_at timestamp with time zone NOT NULL DEFAULT now(),
  assigned_by uuid,
  CONSTRAINT pack_pallet_containers_pkey PRIMARY KEY (id),
  CONSTRAINT pack_pallet_containers_pallet_id_fkey FOREIGN KEY (pallet_id) REFERENCES public.pack_pallets(id),
  CONSTRAINT pack_pallet_containers_container_id_fkey FOREIGN KEY (container_id) REFERENCES public.pack_containers(id),
  CONSTRAINT pack_pallet_containers_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pack_pallet_state_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pallet_id uuid NOT NULL,
  from_state character varying NOT NULL,
  to_state character varying NOT NULL,
  trigger_type character varying NOT NULL CHECK (trigger_type::text = ANY (ARRAY['CONTAINER_ADDED'::character varying, 'ADJUSTMENT_DETECTED'::character varying, 'ADJUSTMENT_RESOLVED'::character varying, 'PALLET_COMPLETE'::character varying, 'PALLET_LOCKED'::character varying, 'DISPATCH_EXECUTED'::character varying, 'STOCK_MOVED'::character varying, 'MANUAL_OVERRIDE'::character varying, 'SYSTEM_AUTO'::character varying, 'CANCELLED'::character varying]::text[])),
  trigger_reference_id uuid,
  trigger_reference_type character varying,
  metadata jsonb DEFAULT '{}'::jsonb,
  performed_by uuid NOT NULL,
  performed_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pack_pallet_state_log_pkey PRIMARY KEY (id),
  CONSTRAINT pack_pallet_state_log_pallet_id_fkey FOREIGN KEY (pallet_id) REFERENCES public.pack_pallets(id),
  CONSTRAINT pack_pallet_state_log_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.pack_pallets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  pallet_number character varying NOT NULL UNIQUE,
  item_id uuid NOT NULL,
  item_code character varying NOT NULL,
  contract_config_id uuid,
  target_qty integer NOT NULL,
  current_qty integer NOT NULL DEFAULT 0,
  container_count integer NOT NULL DEFAULT 0,
  adjustment_container_count integer NOT NULL DEFAULT 0,
  sequence_number integer NOT NULL DEFAULT 1,
  state character varying NOT NULL DEFAULT 'OPEN'::character varying CHECK (state::text = ANY (ARRAY['OPEN'::character varying, 'FILLING'::character varying, 'ADJUSTMENT_REQUIRED'::character varying, 'READY'::character varying, 'LOCKED'::character varying, 'DISPATCHED'::character varying, 'IN_TRANSIT'::character varying, 'CANCELLED'::character varying]::text[])),
  opened_at timestamp with time zone NOT NULL DEFAULT now(),
  filling_at timestamp with time zone,
  adjustment_required_at timestamp with time zone,
  ready_at timestamp with time zone,
  locked_at timestamp with time zone,
  dispatched_at timestamp with time zone,
  in_transit_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  current_warehouse_id uuid,
  packing_list_id uuid,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  row_version integer NOT NULL DEFAULT 1,
  packing_spec_id uuid,
  CONSTRAINT pack_pallets_pkey PRIMARY KEY (id),
  CONSTRAINT pack_pallets_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id),
  CONSTRAINT pack_pallets_contract_config_id_fkey FOREIGN KEY (contract_config_id) REFERENCES public.pack_contract_configs(id),
  CONSTRAINT pack_pallets_current_warehouse_id_fkey FOREIGN KEY (current_warehouse_id) REFERENCES public.inv_warehouses(id),
  CONSTRAINT pack_pallets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT pack_pallets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT pack_pallets_packing_spec_id_fkey FOREIGN KEY (packing_spec_id) REFERENCES public.packing_specifications(id),
  CONSTRAINT pack_pallets_packing_list_id_fkey FOREIGN KEY (packing_list_id) REFERENCES public.pack_packing_lists(id)
);
CREATE TABLE public.pack_proforma_invoice_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proforma_id uuid NOT NULL,
  invoice_id uuid NOT NULL,
  invoice_number character varying NOT NULL,
  invoice_amount numeric NOT NULL,
  pallet_count integer NOT NULL,
  total_quantity integer NOT NULL,
  line_number integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pack_proforma_invoice_items_pkey PRIMARY KEY (id),
  CONSTRAINT pack_proforma_invoice_items_proforma_id_fkey FOREIGN KEY (proforma_id) REFERENCES public.pack_proforma_invoices(id),
  CONSTRAINT pack_proforma_invoice_items_invoice_id_fkey FOREIGN KEY (invoice_id) REFERENCES public.pack_invoices(id)
);
CREATE TABLE public.pack_proforma_invoices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proforma_number character varying NOT NULL UNIQUE,
  customer_code character varying,
  customer_name character varying,
  total_amount numeric NOT NULL DEFAULT 0,
  currency_code character varying NOT NULL DEFAULT 'USD'::character varying,
  status character varying NOT NULL DEFAULT 'DRAFT'::character varying CHECK (status::text = ANY (ARRAY['DRAFT'::character varying, 'CONFIRMED'::character varying, 'STOCK_MOVED'::character varying, 'CANCELLED'::character varying]::text[])),
  total_invoices integer NOT NULL DEFAULT 0,
  total_pallets integer NOT NULL DEFAULT 0,
  total_quantity integer NOT NULL DEFAULT 0,
  proforma_date date NOT NULL DEFAULT CURRENT_DATE,
  stock_movement_id uuid,
  stock_moved_at timestamp with time zone,
  stock_moved_by uuid,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  confirmed_at timestamp with time zone,
  confirmed_by uuid,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  shipment_number character varying,
  cancelled_at timestamp with time zone,
  freight_forwarder text,
  CONSTRAINT pack_proforma_invoices_pkey PRIMARY KEY (id),
  CONSTRAINT pack_proforma_invoices_stock_movement_id_fkey FOREIGN KEY (stock_movement_id) REFERENCES public.inv_movement_headers(id),
  CONSTRAINT pack_proforma_invoices_stock_moved_by_fkey FOREIGN KEY (stock_moved_by) REFERENCES public.profiles(id),
  CONSTRAINT pack_proforma_invoices_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT pack_proforma_invoices_confirmed_by_fkey FOREIGN KEY (confirmed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.packing_audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  packing_request_id uuid NOT NULL,
  action_type character varying NOT NULL CHECK (action_type::text = ANY (ARRAY['PACKING_CREATED'::character varying, 'PACKING_REJECTED'::character varying, 'PACKING_STARTED'::character varying, 'BOX_CREATED'::character varying, 'BOX_DELETED'::character varying, 'STICKER_PRINTED'::character varying, 'PACKING_COMPLETED'::character varying, 'STOCK_MOVEMENT_EXECUTED'::character varying]::text[])),
  performed_by uuid NOT NULL,
  role character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT packing_audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT packing_audit_logs_request_fkey FOREIGN KEY (packing_request_id) REFERENCES public.packing_requests(id),
  CONSTRAINT packing_audit_logs_performed_by_fkey FOREIGN KEY (performed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.packing_boxes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  packing_request_id uuid NOT NULL,
  box_number integer NOT NULL CHECK (box_number > 0),
  box_qty numeric NOT NULL CHECK (box_qty > 0::numeric),
  sticker_printed boolean NOT NULL DEFAULT false,
  sticker_printed_at timestamp with time zone,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  packing_id text,
  is_transferred boolean DEFAULT false,
  transferred_at timestamp with time zone,
  CONSTRAINT packing_boxes_pkey PRIMARY KEY (id),
  CONSTRAINT packing_boxes_request_fkey FOREIGN KEY (packing_request_id) REFERENCES public.packing_requests(id),
  CONSTRAINT packing_boxes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.packing_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  movement_header_id uuid NOT NULL UNIQUE,
  movement_number character varying NOT NULL,
  item_code character varying NOT NULL,
  total_packed_qty numeric NOT NULL CHECK (total_packed_qty > 0::numeric),
  status character varying NOT NULL DEFAULT 'APPROVED'::character varying CHECK (status::text = ANY (ARRAY['APPROVED'::character varying::text, 'REJECTED'::character varying::text, 'PACKING_IN_PROGRESS'::character varying::text, 'PARTIALLY_TRANSFERRED'::character varying::text, 'COMPLETED'::character varying::text])),
  created_by uuid NOT NULL,
  approved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  approved_at timestamp with time zone,
  rejected_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  operator_remarks text,
  supervisor_remarks text,
  transferred_qty integer DEFAULT 0,
  last_transfer_at timestamp with time zone,
  CONSTRAINT packing_requests_pkey PRIMARY KEY (id),
  CONSTRAINT packing_requests_movement_fkey FOREIGN KEY (movement_header_id) REFERENCES public.inv_movement_headers(id),
  CONSTRAINT packing_requests_item_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code),
  CONSTRAINT packing_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT packing_requests_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.packing_specifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  item_id uuid NOT NULL UNIQUE,
  item_code text NOT NULL,
  inner_box_length_mm numeric NOT NULL DEFAULT 0,
  inner_box_width_mm numeric NOT NULL DEFAULT 0,
  inner_box_height_mm numeric NOT NULL DEFAULT 0,
  inner_box_quantity integer NOT NULL DEFAULT 0,
  inner_box_net_weight_kg numeric NOT NULL DEFAULT 0,
  outer_box_length_mm numeric NOT NULL DEFAULT 0,
  outer_box_width_mm numeric NOT NULL DEFAULT 0,
  outer_box_height_mm numeric NOT NULL DEFAULT 0,
  outer_box_gross_weight_kg numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  outer_box_quantity integer NOT NULL DEFAULT 0,
  CONSTRAINT packing_specifications_pkey PRIMARY KEY (id),
  CONSTRAINT packing_specifications_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.items(id)
);
CREATE TABLE public.permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  role_id character varying NOT NULL,
  module character varying NOT NULL,
  action character varying NOT NULL,
  is_allowed boolean DEFAULT true,
  original_module character varying,
  CONSTRAINT permissions_pkey PRIMARY KEY (id),
  CONSTRAINT permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id)
);
CREATE TABLE public.planning_recommendations (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL,
  planning_date date NOT NULL,
  planning_horizon_days integer,
  current_stock numeric,
  reserved_stock numeric,
  forecasted_demand numeric,
  recommended_action character varying NOT NULL,
  recommended_quantity numeric,
  recommended_date date,
  reason text,
  priority character varying DEFAULT 'LOW'::character varying,
  status character varying DEFAULT 'PENDING'::character varying,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT planning_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT planning_recommendations_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  employee_id character varying UNIQUE,
  email character varying NOT NULL UNIQUE CHECK (email::text ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'::text),
  full_name character varying NOT NULL,
  phone character varying,
  department character varying,
  job_title character varying,
  avatar_url text,
  is_active boolean DEFAULT true,
  is_email_verified boolean DEFAULT false,
  must_change_password boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_login_at timestamp with time zone,
  password_changed_at timestamp with time zone,
  role character varying DEFAULT 'L1'::character varying,
  deleted_at timestamp with time zone,
  shift character varying,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.proforma_invoice_mpl_snapshots (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  proforma_id uuid NOT NULL,
  mpl_id uuid,
  mpl_number text,
  line_number integer DEFAULT 1,
  item_code text,
  item_name text,
  part_number text,
  master_serial_no text,
  invoice_number text,
  po_number text,
  total_pallets integer DEFAULT 0,
  total_quantity integer DEFAULT 0,
  total_net_weight_kg numeric DEFAULT 0,
  total_gross_weight_kg numeric DEFAULT 0,
  status text DEFAULT 'SNAPSHOT'::text,
  snapshot_at timestamp with time zone DEFAULT now(),
  CONSTRAINT proforma_invoice_mpl_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.proforma_invoice_mpls (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  proforma_id uuid NOT NULL,
  mpl_id uuid NOT NULL,
  mpl_number character varying NOT NULL,
  invoice_number character varying,
  po_number character varying,
  item_code character varying NOT NULL,
  total_pallets integer NOT NULL,
  total_quantity integer NOT NULL,
  total_gross_weight_kg numeric NOT NULL DEFAULT 0,
  line_number integer NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT proforma_invoice_mpls_pkey PRIMARY KEY (id),
  CONSTRAINT proforma_invoice_mpls_proforma_id_fkey FOREIGN KEY (proforma_id) REFERENCES public.pack_proforma_invoices(id),
  CONSTRAINT proforma_invoice_mpls_mpl_id_fkey FOREIGN KEY (mpl_id) REFERENCES public.master_packing_lists(id)
);
CREATE TABLE public.roles (
  id character varying NOT NULL,
  name character varying NOT NULL,
  description text,
  level integer NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.stock_movements (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_code character varying NOT NULL,
  movement_type character varying NOT NULL,
  transaction_type character varying NOT NULL,
  quantity integer NOT NULL,
  balance_after integer NOT NULL,
  reference_type character varying,
  reference_id uuid,
  reference_number character varying,
  reason text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT stock_movements_pkey PRIMARY KEY (id),
  CONSTRAINT stock_movements_item_code_fkey FOREIGN KEY (item_code) REFERENCES public.items(item_code)
);
CREATE TABLE public.system_settings (
  key character varying NOT NULL,
  value jsonb NOT NULL,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT system_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.temp_credentials (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  temp_password_hash text NOT NULL,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone DEFAULT (now() + '24:00:00'::interval),
  used_at timestamp with time zone,
  is_used boolean DEFAULT false,
  CONSTRAINT temp_credentials_pkey PRIMARY KEY (id),
  CONSTRAINT temp_credentials_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT temp_credentials_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_permissions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  module_name character varying NOT NULL,
  can_view boolean NOT NULL DEFAULT false,
  can_create boolean NOT NULL DEFAULT false,
  can_edit boolean NOT NULL DEFAULT false,
  can_delete boolean NOT NULL DEFAULT false,
  source_role character varying,
  overridden_by uuid,
  overridden_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  override_mode character varying NOT NULL DEFAULT 'grant'::character varying CHECK (override_mode::text = ANY (ARRAY['grant'::character varying, 'full_control'::character varying]::text[])),
  CONSTRAINT user_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT user_permissions_user_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT user_permissions_module_fkey FOREIGN KEY (module_name) REFERENCES public.module_registry(module_key),
  CONSTRAINT user_permissions_overrider_fkey FOREIGN KEY (overridden_by) REFERENCES public.profiles(id)
);